export const MTK_TRADING_STREAM_KEY = 'MTK_TRADING';
export const MTK_TRADING_GROUP_BUY = 'TRADING';
export const MTK_TRADING_GROUP_SELL = 'TRADING2';
export const MTK_TRADING_CONSUMER_BUY_PENDING = 'TRADING_CONSUMER_1';
export const MTK_TRADING_CONSUMER_SELL_PENDING = 'TRADING_CONSUMER_2';
