version: "3.9"

services:
  redis:
    container_name: redis-local
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server /usr/local/conf/redis.conf
    networks:
      - trading_network
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/conf/redis.conf

  # 개발시에는 도커 컴포즈로 안띄우고 인프라만 띄우도록 변경
  server:
    build:
      context: ./server-nest
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - TZ=Asia/Seoul
    networks:
      - trading_network
    command: npm run start:dev
    volumes:
      - /app/node_modules
      - ./server/src:/app/src
      - ./server/env:/app/env

networks:
  trading_network:
    name: trading_network
    driver: bridge
