export const LATEST_CONFIRMED_PRICE = {
  TRADING_KEYPAIR_MTK: 'LATEST_CONFIRMED_PRICE_MTK',
  TRADING_KEYPAIR_RESOURCE: 'LATEST_CONFIRMED_PRICE_RESOURCE',
  TRADING_KEYPAIR_RARE: 'LATEST_CONFIRMED_PRICE_RARE',
};

export const TOP_10_BUY_LIST = {
  TRADING_KEYPAIR_MTK: 'TOP_10_BUY_LIST_MTK',
  TRADING_KEYPAIR_RESOURCE: 'TOP_10_BUY_LIST_RESOURCE',
  TRADING_KEYPAIR_RARE: 'TOP_10_BUY_LIST_RARE',
};
export const TOP_10_SELL_LIST = {
  TRADING_KEYPAIR_MTK: 'TOP_10_SELL_LIST_MTK',
  TRADING_KEYPAIR_RESOURCE: 'TOP_10_SELL_LIST_RESOURCE',
  TRADING_KEYPAIR_RARE: 'TOP_10_SELL_LIST_RARE',
};
